const faker = require('faker');
let sentences = [];
let prices = [];
let booleans = [false, true];
let companyNames = [];
let words = [];

// //Array of faker sentences
// let sentence = '';
// for (let i = 1; i <= 100; i++) {
//   sentence = faker.lorem.sentence();
//   sentences.push(sentence);
// }
// console.log('SENTENCES: ', sentences);


// //Array of faker prices
// let price = 0;
// for (let j = 1; j <= 100; j++) {
//   price = faker.commerce.price();
//   prices.push(price);
// }
// console.log('PRICES: ', prices);


// //Array of faker company names
// let companyName = '';
// for (let k = 1; k <= 100; k++) {
//   companyName = faker.company.companyName();
//   companyNames.push(companyName);
// }
// console.log('COMPANY NAMES: ', companyNames);


// //Array of faker words
// let word = '';
// for (let l = 1; l <= 100; l++) {
//   word = faker.lorem.words();
//   words.push(word);
// }
// console.log('WORDS: ', words);

sentences = [ 'Dignissimos et quis.',
  'Id quod praesentium inventore id adipisci ab voluptas.',
  'Quo nesciunt eum inventore amet rerum hic doloribus voluptatibus.',
  'Reprehenderit et ea sint.',
  'Est et eum.',
  'Laborum sapiente est commodi eos iusto neque maiores illo et.',
  'Dolore atque sed modi vitae et maiores delectus illo provident.',
  'Id dicta est cumque dolorum voluptas doloribus.',
  'Veritatis voluptate at nihil.',
  'Voluptas est qui eum id eum.',
  'Qui odit sed itaque.',
  'Sed enim esse voluptate autem fugit beatae repudiandae quae.',
  'Accusamus voluptatem repellat recusandae voluptas temporibus id consectetur et.',
  'Beatae aliquam dolorum officia magnam maxime ut debitis omnis.',
  'Fuga officiis qui.',
  'Unde nulla fuga.',
  'Nobis sunt repudiandae eum voluptatem.',
  'Temporibus tenetur eos totam facere sapiente eius ducimus.',
  'Vel ullam ullam voluptatem sit provident quasi libero velit impedit.',
  'Labore at culpa reprehenderit nostrum minus odio.',
  'Quisquam provident iste magni dolorum dolore nobis facilis.',
  'Ad quod sunt.',
  'Et mollitia ullam ut placeat rem quibusdam.',
  'Necessitatibus harum ducimus.',
  'Optio consequuntur voluptatem voluptatem eos.',
  'Nulla enim explicabo ut commodi ex.',
  'Laboriosam ut autem.',
  'Voluptatum quas facilis sit.',
  'Voluptas quos est ut voluptas odit accusamus inventore dolorum.',
  'Deleniti fugiat corrupti laboriosam hic consequatur debitis nobis dignissimos facere.',
  'Et autem dolores error amet dignissimos quae autem omnis rerum.',
  'Sapiente aperiam recusandae ipsum et et eveniet aut.',
  'Non earum tempore inventore consequatur consectetur est dolorem quo.',
  'Quo enim aut dicta.',
  'Sit optio vel qui debitis debitis consequuntur voluptatibus nobis maiores.',
  'Aut ipsa cupiditate rem magnam voluptatem libero delectus possimus eligendi.',
  'Explicabo quasi maiores alias rerum amet culpa dolorem et ipsa.',
  'Consectetur rerum voluptas numquam debitis et debitis eveniet qui sit.',
  'Nisi velit cupiditate optio.',
  'Ipsum laudantium eaque asperiores dicta veniam dolores eius beatae.',
  'Cum deserunt sed.',
  'Autem similique et quidem itaque harum et explicabo.',
  'Voluptas molestiae voluptatem voluptatem quidem similique.',
  'Enim velit pariatur tenetur repellendus et sint dolorem aut mollitia.',
  'Qui quibusdam consequatur asperiores neque fugit et fugit mollitia numquam.',
  'Est laborum quidem necessitatibus quisquam omnis.',
  'Maiores in itaque accusantium.',
  'Ipsam nihil qui doloribus.',
  'Ut quod et et doloremque eos laborum earum.',
  'Ipsa quia cupiditate aut sapiente.',
  'Mollitia enim magni.',
  'Eius ut dolore impedit reiciendis.',
  'Inventore molestiae accusamus rem vel suscipit illum.',
  'Veniam quis quidem odit.',
  'Atque enim saepe vel cupiditate maxime aperiam qui.',
  'Ad asperiores voluptatem iure ea est maxime quasi quisquam.',
  'Mollitia repellat dolorum voluptas sint quis.',
  'Unde quo est ut maxime.',
  'Maxime cupiditate ratione impedit corporis inventore qui corrupti aspernatur libero.',
  'Cumque odio doloribus molestias est doloribus dolorem facilis.',
  'Officiis quas consequatur ducimus quia.',
  'Ipsum aut et id et labore beatae quasi laudantium.',
  'Expedita placeat excepturi magnam molestiae velit earum voluptatem accusamus.',
  'Omnis consectetur doloribus.',
  'Maxime rerum ratione mollitia quis ut ab consequatur quo deleniti.',
  'Molestiae eos in alias sunt et quia quaerat culpa quo.',
  'Eos sit praesentium impedit qui omnis in aspernatur dolore id.',
  'Maiores aut repudiandae earum debitis asperiores.',
  'Assumenda cupiditate repellendus eius ut id ipsam earum.',
  'Ad recusandae eaque dignissimos non accusamus nihil.',
  'Quos cupiditate id quibusdam iure.',
  'Sit qui laboriosam ut non ut ipsum reprehenderit.',
  'Excepturi quis sit unde odio sed minus.',
  'Qui incidunt deleniti.',
  'Inventore adipisci molestias.',
  'Sequi quia non autem veritatis qui nesciunt cupiditate et et.',
  'Inventore exercitationem eum accusamus rerum optio dolorem sint suscipit quod.',
  'Itaque voluptas sint voluptas laudantium sed.',
  'Voluptatem labore et debitis dicta soluta delectus quam eius facere.',
  'Maxime ipsum vero autem quia quas ullam illum necessitatibus vel.',
  'Est et et nesciunt quas quae quisquam.',
  'Officiis corporis ad nihil vel exercitationem autem vel mollitia.',
  'Autem voluptates similique quaerat non vel corrupti aut incidunt.',
  'Corrupti optio adipisci aliquid aut nemo earum assumenda.',
  'Tempora velit laboriosam quo voluptatem.',
  'Ipsum beatae non sit qui qui molestiae omnis.',
  'Nobis dolores corrupti provident nesciunt vitae nihil occaecati minus.',
  'Ea sit eos fuga eligendi cumque minima quae eveniet sint.',
  'Dolorem exercitationem reprehenderit occaecati aut eligendi.',
  'Quasi et totam.',
  'Corrupti voluptatem magni quae necessitatibus sint molestiae maiores dolore quis.',
  'Assumenda error est maxime veniam voluptatem nam.',
  'Nobis et voluptas qui aut sint repudiandae est quae explicabo.',
  'Aliquid voluptatem maxime optio ut culpa aliquid quia consequuntur.',
  'Voluptatibus quas consequatur perspiciatis.',
  'Eius ut excepturi quam quo est omnis autem.',
  'Et corporis dolore eaque quia eveniet et.',
  'Rerum commodi magnam eum.',
  'Et quae voluptas.',
  'Officiis minus omnis.' ];

prices = [ '329.00',
  '734.00',
  '131.00',
  '708.00',
  '419.00',
  '654.00',
  '666.00',
  '265.00',
  '143.00',
  '766.00',
  '779.00',
  '29.00',
  '90.00',
  '701.00',
  '682.00',
  '761.00',
  '780.00',
  '876.00',
  '109.00',
  '641.00',
  '667.00',
  '930.00',
  '819.00',
  '95.00',
  '957.00',
  '489.00',
  '869.00',
  '354.00',
  '981.00',
  '945.00',
  '210.00',
  '440.00',
  '924.00',
  '563.00',
  '861.00',
  '218.00',
  '436.00',
  '457.00',
  '881.00',
  '850.00',
  '18.00',
  '81.00',
  '794.00',
  '727.00',
  '598.00',
  '646.00',
  '295.00',
  '567.00',
  '713.00',
  '193.00',
  '215.00',
  '561.00',
  '527.00',
  '870.00',
  '213.00',
  '994.00',
  '317.00',
  '401.00',
  '719.00',
  '814.00',
  '473.00',
  '797.00',
  '434.00',
  '693.00',
  '653.00',
  '575.00',
  '893.00',
  '306.00',
  '313.00',
  '285.00',
  '418.00',
  '121.00',
  '510.00',
  '607.00',
  '2.00',
  '320.00',
  '297.00',
  '985.00',
  '216.00',
  '134.00',
  '253.00',
  '127.00',
  '155.00',
  '991.00',
  '112.00',
  '290.00',
  '965.00',
  '49.00',
  '209.00',
  '85.00',
  '664.00',
  '394.00',
  '854.00',
  '221.00',
  '993.00',
  '174.00',
  '213.00',
  '625.00',
  '665.00',
  '827.00' ];

companyNames = [ 'Tillman, Stracke and Schaefer',
  'Franecki, Hagenes and Schneider',
  'Nolan - Zemlak',
  'Witting - Hilpert',
  'Ryan and Sons',
  'Auer Inc',
  'Schneider LLC',
  'Lind LLC',
  'Schmidt, Stamm and Paucek',
  'Rosenbaum, Strosin and Prohaska',
  'Sporer LLC',
  'Stroman - Nikolaus',
  'Hackett, Mante and Muller',
  'Cummings - Satterfield',
  'Runolfsdottir - Wunsch',
  'Kihn Inc',
  'Miller Group',
  'Koss, O\'Conner and Waters',
  'Lowe, Bahringer and Ankunding',
  'Buckridge LLC',
  'Littel LLC',
  'Abernathy, Lehner and Hilpert',
  'Dickens - Williamson',
  'Howell, Bogan and Mante',
  'Kozey and Sons',
  'Blick, Kemmer and Daniel',
  'Beatty LLC',
  'Connelly - Kertzmann',
  'Feest and Sons',
  'Wisozk - Lynch',
  'Smith, Swift and DuBuque',
  'Connelly, Koelpin and Gislason',
  'Hermann, Goyette and O\'Connell',
  'Durgan - Langworth',
  'Mosciski, Schiller and Konopelski',
  'Will Group',
  'Reilly - Hodkiewicz',
  'Hessel LLC',
  'Bergnaum, Herman and Marvin',
  'Mohr, Kunde and Maggio',
  'Welch Inc',
  'Eichmann Inc',
  'Denesik, Zboncak and Morar',
  'Gaylord, Veum and Schultz',
  'Olson, Miller and Koch',
  'Kovacek - Barton',
  'Smith, Rempel and Jones',
  'Howell - Goodwin',
  'Veum - Crooks',
  'Leuschke - Jacobs',
  'Schmitt LLC',
  'Waelchi, Brakus and Schmitt',
  'Powlowski, Pouros and Wintheiser',
  'Hirthe and Sons',
  'Lemke and Sons',
  'Blick - Cartwright',
  'Keebler, Borer and Johnson',
  'Satterfield, Rolfson and Ruecker',
  'Kohler Group',
  'Beier, Stracke and Larkin',
  'Adams - Lind',
  'Hyatt, Miller and Mohr',
  'Gulgowski Group',
  'Bartell - Oberbrunner',
  'Reilly LLC',
  'Wyman Group',
  'Lemke - Hartmann',
  'Jacobs, Morissette and Nienow',
  'Kerluke, Wiegand and Orn',
  'Keeling, Rippin and Becker',
  'Brekke - Greenfelder',
  'Roob, Raynor and Roob',
  'Leannon - Denesik',
  'Willms - Hansen',
  'DuBuque, O\'Reilly and Grimes',
  'Yost - Langworth',
  'Kilback LLC',
  'Fahey and Sons',
  'Schaefer - Denesik',
  'Okuneva LLC',
  'Murphy Group',
  'Kautzer Inc',
  'Corkery, Blanda and Jones',
  'Dibbert and Sons',
  'Dare - Christiansen',
  'Willms Inc',
  'D\'Amore LLC',
  'Ullrich LLC',
  'Emard LLC',
  'Wehner, Pouros and Braun',
  'Barrows Group',
  'Halvorson - Larkin',
  'Zboncak and Sons',
  'Howell, Ruecker and Borer',
  'Rempel - Rutherford',
  'Beahan - Herman',
  'Rohan - Morar',
  'Senger, Jacobson and Effertz',
  'Bailey, Grimes and Keebler',
  'Beatty Inc' ];

words = [ 'blanditiis voluptate voluptas',
  'sed et omnis',
  'soluta dolorem et',
  'voluptas culpa possimus',
  'distinctio vero corporis',
  'voluptates facilis hic',
  'culpa praesentium est',
  'voluptatem exercitationem neque',
  'aliquid totam ut',
  'et at veniam',
  'id autem voluptatem',
  'rerum est sint',
  'aut vel possimus',
  'delectus quos amet',
  'tenetur in atque',
  'doloribus ipsam repellat',
  'aut labore reprehenderit',
  'rerum ut fugit',
  'molestias qui nesciunt',
  'reprehenderit quos quaerat',
  'et voluptatem totam',
  'facere culpa ea',
  'qui consequatur expedita',
  'et cum ut',
  'mollitia ut voluptates',
  'vel doloremque magnam',
  'sint provident voluptates',
  'laboriosam delectus autem',
  'reiciendis impedit explicabo',
  'doloribus tempora omnis',
  'in doloremque aut',
  'sint est est',
  'vero repellat praesentium',
  'ullam ut deleniti',
  'natus odit fugit',
  'autem in perferendis',
  'odit id tempora',
  'aut maiores quis',
  'odio velit aliquid',
  'unde doloribus dignissimos',
  'ipsum quasi temporibus',
  'est ut dolorem',
  'veniam consequuntur sunt',
  'asperiores est ad',
  'est est voluptas',
  'eius sit incidunt',
  'suscipit error officia',
  'et error incidunt',
  'blanditiis sequi error',
  'omnis totam vel',
  'eius et rerum',
  'unde odio praesentium',
  'error mollitia consectetur',
  'non in iste',
  'enim itaque reprehenderit',
  'ab culpa cupiditate',
  'nihil laudantium quod',
  'corrupti libero quibusdam',
  'eum tempora libero',
  'id quia officiis',
  'voluptates velit corporis',
  'nobis ipsum similique',
  'doloribus sint aut',
  'perspiciatis necessitatibus quia',
  'animi est quo',
  'est nulla autem',
  'provident perspiciatis consequatur',
  'perferendis voluptatem quibusdam',
  'laborum fuga et',
  'sit itaque praesentium',
  'officia omnis autem',
  'blanditiis occaecati aut',
  'sed aut quas',
  'quia sunt minus',
  'consequatur sit natus',
  'dignissimos ipsa dolores',
  'omnis repellendus qui',
  'officia omnis in',
  'est ut molestiae',
  'sunt quidem nihil',
  'quibusdam dolores mollitia',
  'et dolorem quia',
  'veniam modi expedita',
  'perspiciatis est molestias',
  'quos quibusdam eos',
  'velit sit illum',
  'omnis sit qui',
  'a ea dolor',
  'aut velit commodi',
  'voluptatem repellendus mollitia',
  'nobis et et',
  'laudantium nam praesentium',
  'quia qui voluptatem',
  'ad fuga voluptas',
  'magnam magni ad',
  'veritatis aliquid nam',
  'ex qui voluptatem',
  'non doloribus adipisci',
  'laudantium aliquam sequi',
  'sunt placeat enim' ];

module.exports = {
  sentences,
  prices,
  booleans,
  companyNames,
  words,
};